### ISSUE TITLE
ssh: unable to authenticate

### ISSUE THREAD

**Issue by ayarosh** [JWDobken/terraform-hcloud-kubernetes#22]
I'm getting the following error when applying plan:
`Error: timeout - last error: SSH authentication failed (root@NODE_PUBLIC_IP:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`
But provider doesn't contain the [inputs](https://registry.terraform.io/modules/JWDobken/kubernetes/hcloud/latest?tab=inputs) for ssh private key.

**Comment by JWDobken** [comment]
Hi @ayarosh,

You don't have to provide the private key to the provider, but you do need to add the key to your keychain so Terraform can ssh into the nodes from local:

```cmd
ssh-add ~/.ssh/hcloud
```

To add the key permenantly, there is a thread [here](https://apple.stackexchange.com/questions/48502/how-can-i-permanently-add-my-ssh-private-key-to-keychain-so-it-is-automatically).

If you have issues, let me know.

**Comment by ayarosh** [comment]
> Hi @ayarosh,
> 
> You don't have to provide the private key to the provider, but you do need to add the key to your keychain so Terraform can ssh into the nodes from local:
> 
> ```batchfile
> ssh-add ~/.ssh/hcloud
> ```
> 
> To add the key permenantly, there is a thread [here](https://apple.stackexchange.com/questions/48502/how-can-i-permanently-add-my-ssh-private-key-to-keychain-so-it-is-automatically).
> 
> If you have issues, let me know.

I've tried to provide that.
It wasn't help.

**Comment by JWDobken** [comment]
and the ssh agent is up-and-running?

**Comment by kscarlett** [comment]
I was having a similar issue just now, where I was getting the same error message, but I was able to ssh in manually without providing any additional input.

I figured it couldn't be that the key wasn't in the keychain, because it was the default `id_rsa` and it worked manually, however it worked after I ran `ssh-add` in the same terminal session. I'm not sure why it didn't work when manual ssh worked perfectly, so that's a bit strange.

Versions added in case it's a bug somewhere:

- macOS 10.14.6
- OpenSSH_7.9p1, LibreSSL 2.7.3
- Terraform v0.15.4 and 1.0.7
